-- 002_password_migration.sql — 将存量明文密码升级为 pbkdf2 哈希
-- 
-- 此迁移在服务启动时自动执行（如果 schema_version < 2）。
-- 仅处理仍为明文的旧密码行；已为 pbkdf2 格式的行不受影响。

-- 注意：由于 pbkdf2 哈希需要 Python 计算，真正的密码迁移由
-- db_verify_password 在用户登录时自动触发。此迁移仅记录版本号，
-- 不做危险操作（无法在 SQL 中安全地批量哈希密码）。
-- 
-- 生产环境部署步骤：
--   1. 部署新代码（含此迁移）
--   2. 用户登录时自动升级密码
--   3. 1-2 周后，确认 db_needs_password_migration() 返回 0
--   4. 可选：手动清理遗留明文行
